spring.application.name=notification-service

# Notification service ka port
server.port=8081

# Kafka configurations
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest